### ISSUE TITLE
Add compatibility with http-errors to jsonapi_exception_formatter

### ISSUE THREAD

**Issue by pysalt** [AdCombo/flask-combo-jsonapi#1]
Currently the `jsonapi_exception_formatter` decorator normally handles `JsonApiException` exceptions only. Source:
```python
        try:
            return func(*args, **kwargs)
        except JsonApiException as e:
            return make_response(jsonify(jsonapi_errors([e.to_dict()])),
                                 e.status,
                                 headers)
        except Exception as e:
             ...
```
However, plugins can implement their own errors, which can be correlated with `JsonApiException` errors. This is necessary to avoid handling errors such as critical.
moreover, this library integrates with flask and should support its standard http-errors.
I suggest in the block `except Exception` to check the attribute code (or status_code) of the error and try to correlate it with the JSONAPI error. If a match is found, then do not log this error, but return the corresponding JSONAPI error.
Example:
```python
except Exception as e:
    http_ex = format_http_exception(e)
    if http_ex:
        return make_response(jsonify(jsonapi_errors([http_ex.to_dict()])),
                                 http_ex.status,
                                 headers)
```

**Comment by Znbiz** [comment]
Resolved
Pull request: https://github.com/AdCombo/flask-rest-jsonapi/pull/2
