### ISSUE TITLE
Rename this repo and python package

### ISSUE THREAD

**Issue by mahenzon** [AdCombo/flask-combo-jsonapi#10]
Rename repo from `flask-rest-jsonapi` so that it's easier to search and/or allows it to be added to the `JSON:API` site as a separate project? In addition it makes it clearer to users that it's not the exact same project, especially in case this API diverges from upstream.

**UPD:** new name will be `flask-combo-jsonapi`

Flow:
- [x] create a separate branch for renaming all imports and other names
- [x] do the same in combojsonapi
- [x] refactor our production to use new name
- [x] run tests
- [x] merge that branch:
   1. merge to master, tag 1.0.0
   2. rename repo
   3. update requirement in combojsonapi
   4. release combojsonapi @1.0.0 

- [ ] deploy to pypi #11

**Comment by Znbiz** [comment]
I propose to rename it to `flask-combo-jsonapi`
JSON:API on steroids

**Comment by roman-adcomo** [comment]
Done :)

**Comment by mahenzon** [comment]
Here's a thing: our production depends on this repo.
So, the way to implement this rename is:
- create a separate branch for renaming all imports and other names
- refactor our production to use new name
- run tests
- merge that branch
- deploy to pypi #11 
- change dependency in our production
- run tests again, deploy

**Comment by multimeric** [comment]
In the short term you can rename the repo but not the python module I would hope? Which would give you most of the above advantages without breaking production.

**Comment by mahenzon** [comment]
Yeah. Anyway the work is already done. Waiting for the last manual testing. Renaming the package in the production was the easiest part. 
The changes will be merged to develop and master in a day or so

**Comment by mahenzon** [comment]
Version `1.0.0` released https://github.com/AdCombo/flask-combo-jsonapi/releases/tag/1.0.0

Pending publish to pypi
