### ISSUE TITLE
Error handling exception in format_http_exception

### ISSUE THREAD

**Issue by mahenzon** [AdCombo/flask-combo-jsonapi#16]
Sometimes an error with invalid value can be passed to the `format_http_exception. And it fails here:
https://github.com/AdCombo/flask-combo-jsonapi/blob/7558e71ffb7a9c5c898a3d7cf860dcb334677cc7/flask_combo_jsonapi/errors.py#L30-L34

```
  File "/.../flask-combo-jsonapi/flask_combo_jsonapi/errors.py", line 32, in format_http_exception
    status = int(code)
ValueError: invalid literal for int() with base 10: 'f405'
```

Maybe changing to `except (TypeError, ValueError):` will help

**Comment by pysalt** [comment]
interesting case. I did not take into account the appearance of a string that can be interpreted by a number with a different basis.
