### ISSUE TITLE
How to reinitialize the query string manager filter and sort

### ISSUE THREAD

**Issue by codedsun** [AdCombo/flask-combo-jsonapi#47]
I am creating a plugin which will dasherize the calls from API in filter and sort .

Example: starts-at will be converted to starts_at

But how do I initalize the filter and sort in query string manager to the new dict which I created(which has dasherized parameters).

```
def _update_query(
        self,
        *args,
        query: Query = None,
        qs: QueryStringManager = None,
        view_kwargs=None,
        self_json_api=None,
        **kwargs,
    ) -> Query:
```

**Comment by dmitrymishanov** [comment]
Hello! Looks like there is no way to change default `QueryStringManager` now. But I think that it won't be too hard to define custom QSManager for Api, set it or default QSManager for all resources in `flask_combo_jsonapi.api.Api.route` and then use defined (or default) class in request methods instead of just `QSManager`.
Seems like we don't need a separate plugin for that.

It would be great if you would like to contribute that to the library:)

**Comment by codedsun** [comment]
@dmitrymishanov - You meant that I shall pass the custom QueryStringManager in
```
api.route(
    RoleDetail,
    'role_detail',
    'roles/<int:id>',
    '/panel-permissions/<int:role_id>/roles',
)
```

or you want me to define qs manager in every request methods?
```
 def get(self, *args, **kwargs):
        qs = QSManager(request.args, self.schema)
```

What will be the way to solve this problem as option 2 would be then done for every call and every method which is redundant for the whole project.

**Comment by dmitrymishanov** [comment]
No, I meant something like this:
```py
api_json = Api(
        app,
        decorators=(),
        plugins=(
            api_spec,
            EventPlugin(),
            PermissionPlugin(strict=True),
            PostgreSqlJSONB(),
        ),
        qs_manager_class=MyCustomQSManager
    )
```
Then in `flask_combo_jsonapi.api.Api.route`:
```py
for i_plugin in self.plugins:
            try:
                i_plugin.before_route(resource=resource, view=view, urls=urls, self_json_api=self, **kwargs)
            except PluginMethodNotImplementedError:
                pass
        setattr(resource, 'plugins', self.plugins)
        
        ### here it is
       setattr(resource, 'qs_manager_class', self.qs_manager_class)
```

And then in get/post/patch methods use `self.qs_manager_class` instead of just `QSManager`.
