### ISSUE TITLE
Update SQLAlchemy to 1.4+

### ISSUE THREAD

**Issue by igieon** [AdCombo/flask-combo-jsonapi#52]
Hi is any special reason not to use sqlalchemy 1.4.x ?

**Comment by mahenzon** [comment]
Hi! Sorry for late reply. The only reason is that it wasn't tested yet. Will update this issue to track SQLAlchemy update

**Comment by mahenzon** [comment]
hey, I checked with the latest alchemy and got some unexpected warnings. I didn't get any errors, but I'm not confident we can use the latest alchemy

**Comment by igieon** [comment]
Ok, no problem. We use it with 1.4 with no problem if anything will be found i come with pull request.

**Comment by igieon** [comment]
> hey, I checked with the latest alchemy and got some unexpected warnings. I didn't get any errors, but I'm not confident we can use the latest alchemy

Can you share what warnings you get ?

**Comment by igieon** [comment]
Also you approve #63  where is move to flask 2.0> and sqlalchemy 1.4 from my point of view its better to restrict lower bound so if someone wants to have newer version and want to experiment that he dont need to make own release of flask-combo
